name: Build

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: cp .env.dist .env
      - name: Build container
        run: docker build . -t jazle --target base
      - name: Test
        run: docker run jazle npm run test
      - name: Lint
        run: docker run jazle npm run lint
